### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by liushifu12138** [hysts/pytorch_mpiigaze_demo#31]
(pytorch3d) C:\Users\Admin\Desktop\pytorch_mpiigaze_demo-master>ptgaze --mode mpiigaze --camera sample_params.yaml
INFO:ptgaze.main:mode: MPIIGaze
device: cpu                    
model:
  name: resnet_preact
face_detector:
  mode: mediapipe
  dlib_model_path: C:/Users/Admin/.ptgaze/dlib/shape_predictor_68_face_landmarks.dat
  mediapipe_max_num_faces: 3
  video_path: null
  output_dir: null
  output_file_extension: avi
  head_pose_axis_length: 0.05
  gaze_visualization_length: 0.05
  show_bbox: true
  show_head_pose: false
  show_landmarks: false
  show_normalized_image: false
  show_template_model: false
PACKAGE_ROOT: C:/Users/Admin/anaconda3/envs/pytorch3d/Lib/site-packages/ptgaze

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
When I run the demo on WIN, Frame doesn't show Gaze Estimation?just turned on the camera

**Comment by hysts** [comment]
@liushifu12138 
As I don't have a Windows environment, I can't check it myself, but what happens if you run the demo on [this sample image](https://github.com/hysts/pytorch_mpiigaze_demo/blob/master/assets/inputs/image00.jpg)?

**Comment by liushifu12138** [comment]
ptgaze --mode mpiigaze --video video04.mp4 --device cuda
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\pytorch3d\lib\runpy.py", line 197, in _run_module_as_main                              
    return _run_code(code, main_globals, None,                                                                               
  File "C:\Users\Admin\anaconda3\envs\pytorch3d\lib\runpy.py", line 87, in _run_code                                         
    exec(code, run_globals)                                                                                                  
  File "C:\Users\Admin\anaconda3\envs\pytorch3d\Scripts\ptgaze.exe\__main__.py", line 7, in <module>                         
  File "C:\Users\Admin\anaconda3\envs\pytorch3d\lib\site-packages\ptgaze\main.py", line 137, in main                         
    generate_dummy_camera_params(config)                                                                                     
  File "C:\Users\Admin\anaconda3\envs\pytorch3d\lib\site-packages\ptgaze\utils.py", line 131, in generate_dummy_camera_params
    with open('/tmp/camera_params.yaml', 'w') as f:                                                                          
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/camera_params.yaml'

**Comment by liushifu12138** [comment]
thank you

**Comment by hysts** [comment]
@liushifu12138 
I just updated the repo and the PyPI package. Can you check if it works on your Windows environment?

**Comment by liushifu12138** [comment]
IT IS OK，thanks you

**Comment by liushifu12138** [comment]
but ptgaze --mode eth-xgaze --camera sample_params.yaml  still can't do real-time sight estimation

**Comment by hysts** [comment]
What do you mean? Is it too slow? If you're talking about inference being too slow, I can't help it. Using CUDA would make it faster, though.

**Comment by liushifu12138** [comment]
I mean when I run ptgaze --mode eth-xgaze --camera sample_params.yaml, there is no line of gaze estimation

**Comment by hysts** [comment]
@liushifu12138 
As I said earlier, I don't have a Windows environment, and it works on my Ubuntu and Mac environments, so I think the problem is due to the difference in environments, but I can't help you with just the information that it doesn't work.
Would you provide any information that might help me narrow down the problem? Doesn't it show anything when you run it on [this sample image](https://github.com/hysts/pytorch_mpiigaze_demo/blob/master/assets/inputs/image00.jpg)? Is the face bounding box shown? Are there any errors?

Using docker may be the easiest solution to your problem.

**Comment by liushifu12138** [comment]
It can run successfully on Image and video, but when I run ptgaze --mode eth-xgaze --camera sample_params.yaml, I just open the camera and have no face bounding box shown.
Anyway, thanks for your help

**Comment by hysts** [comment]
@liushifu12138 
Thanks for the info.
But that's weird. If it works for videos, it should work for the camera too.

It  seems your face is not detected, but doesn't it work even if you turn your face toward the camera and get close enough?
The default face detector is MediaPipe, but the model is mainly for selfie-like images, so that may be the cause. What happens when you specify `--face-detector face_alignment_sfd`?
